### ISSUE TITLE
Debugger bugs and improvements

### ISSUE THREAD

**Issue by radumereuta** [kframework/llvm-backend#267]
1. I want to be able to set a breakpoint on every function with a single command.
This will allow me to reach a problematic area much faster.
2. I can't set a breakpoint on a function sometimes:
```
module TEST
  imports K-REFLECTION
  imports INT
  configuration <k> #parseKORE("\\dv{Int{}}(\"1\")"):Int </k>
endmodule
(gdb) break domains.k:889
No line 889 in file "domains.k".
```

```
module TEST
  imports DOMAINS
  imports K-REFLECTION
  syntax Path ::= r"[\\\\./a-zA-Z0-9_-][\\\\./a-zA-Z0-9_-]*" [token]

  configuration
      <k> #parseKORE("\\dv{Int{}}(\"1\")"):Int </k>
      <p> $PATH:Path </p>
  rule <k> _:Int => .K </k>
endmodule
(gdb) break domains.k:889
Breakpoint 1 at 0x293c20: file /home/radu/work/k/k-distribution/target/release/k/include/builtin/domains.k, line 985.
```
And again, the line number is way off. What does it even represent?

**Comment by dwightguth** [comment]
You can do number 1 with `rbreak Lbl`.

Number 2 I might be able to make work... I'll have to try it and see. But in the meantime, you can set a breakpoint on a function with a hook that has the attribute FOO.bar by setting a breakpoint on hook_FOO_bar.

**Comment by dwightguth** [comment]
It doesn't look like my idea for how to make it possible to set breakpoints on hooks via their line number in a K file will work. We are limited in this case by how dwarf info works, and how we generate the runtime of K. So I am going to close this.
