### ISSUE TITLE
Support for new rule format

### ISSUE THREAD

**Issue by MirceaS** [kframework/llvm-backend#417]
The LLVM backend should be updated so as to accept a new format for rules: https://github.com/kframework/k/issues/1945

There is already a PR up in the frontend set up to emit the new format: https://github.com/kframework/k/pull/2061
It just has to also be supported in the LLVM backend.

**Comment by SchmErik** [comment]
I'm trying the code in the pull request and it's failing on cases where the `ensures` clause does not exist in the code that I'm compiling. Is this expected? Is there an `ensures` in some other place that I'm not seeing? Here's the example that I'm working with...

**Comment by SchmErik** [comment]
Oh wait, I did kompile -v and I see that kompile includes several files like prelude.md and domains.md. It's likely that these include `ensures`
