### ISSUE TITLE
Remove uses of PointerType::getElementType and Type::getPointerElementType

### ISSUE THREAD

**Issue by dwightguth** [kframework/llvm-backend#440]
In future versions of llvm, it is known that the derived pointer type T* where T is the type pointed to is going to be replaced by a generic base type `ptr`. This means that code in the LLVM backend that relies on the methods `PointerType::getElementType` and `Type::getPointerElementType` are not going to work in these future versions of LLVM. Thus, we are going to have to modify the llvm backend to remove all calls to these functions and independently track the information needed in the code generator in order to avoid needing access to these functions.

There are about 21 calls to these methods currently in the code, in CreateTerm.cpp, Decision.cpp, and EmitConfigParser.cpp. Most of these are simply a matter of convenience, so it shouldn't be too hard to clean up. There may be a couple that require a bit more work in the form of information passed between methods.

We should try to find time to do this proactively so that we don't have to do it all at once when LLVM 14 or whatever future version of LLVM finally enables opaque pointer types is released.

**Comment by Baltoli** [comment]
@SchmErik, did #457 fix all of the instances of `get[pointer]ElementType` that we need to get rid of?
