### ISSUE TITLE
Issues building on Arch Linux

### ISSUE THREAD

**Issue by ehildenb** [kframework/llvm-backend#67]
On Arch Linux, I had to take several steps to build the LLVM backend (and still am not able to):

Downgrade to llvm-6.0 and clang-6.0 (default is 7.0 on Arch).

I had to manually change `llvm-backend/pom.xml` (since by default the executables are named different on Arch, and the pom.xml doesn't seem to allow environment based overrides):

```
diff --git a/llvm-backend/pom.xml b/llvm-backend/pom.xml
index be72f0cf7..4e0da88f9 100644
--- a/llvm-backend/pom.xml
+++ b/llvm-backend/pom.xml
@@ -49,8 +49,8 @@
               <target>
                 <mkdir dir="${project.build.directory}/build" />
                 <exec executable="cmake" dir="${project.build.directory}/build" failonerror="true">
-                  <env key="CC" value="clang-6.0" />
-                  <env key="CXX" value="clang++-6.0" />
+                  <env key="CC" value="clang" />
+                  <env key="CXX" value="clang++" />
                   <arg value="-DCMAKE_BUILD_TYPE=${project.build.type}" />
                   <arg value="${project.basedir}/src/main/native/llvm-backend" />
                 </exec>
```

It still does not build, with the following CMake error:

```
CMake Error at CMakeLists.txt:22 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 6) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/dev/src/k-pr/llvm-backend/src/main/native/llvm-backend/build/CMakeFiles/CMakeOutput.log".
```

@dwightguth any ideas?

**Comment by dwightguth** [comment]
If you have llvm 6 installed on that machine that sounds like a bug in the distro package.

**Comment by dwightguth** [comment]
You should look and see whether it got installed in an unusual place cmake doesn't know about.

**Comment by ehildenb** [comment]
Looks like they are not there:

```
[ehildenb@office-server ~]% sudo find / -name LLVMConfig.cmake
find: ‘/proc/13190’: No such file or directory
find: ‘/proc/13227’: No such file or directory
[1] [ehildenb@office-server ~]% sudo find / -name llvm-config.cmake
[ehildenb@office-server ~]% 
```

**Comment by ehildenb** [comment]
Ok, to get the llvm-backend to build directly (still not building directly in K using `mvn package -DskipTests`):

-   Download versions 6.0.1-2 of the packages llvm, llvm-libs, and clang. Find in the Arch Linux Archive (https://wiki.archlinux.org/index.php/Arch_Linux_Archive) at https://archive.archlinux.org/packages/c/clang/, https://archive.archlinux.org/packages/l/llvm-libs/, and https://archive.archlinux.org/packages/l/llvm/.

-   Optionally move the downloaded packages to `/var/cache/pacman/pkg/` (where pacman stores packages). Make sure they are owned by `root` with `chown root:root /var/cache/pacman/pkg/PACKAGE_NAME`.

-   Make sure upgraded versions are not installed using `sudo pacman -R llvm llvm-libs clang`.

-   Install downgraded versions using `sudo pacman -U /PATCH/TO/PACKAGES/{clang,llvm,llvm-libs}-6.0.1-2-x86_64.pkg.tar.xz`.

-   Follow the normal install instructions, but with `CC=clang` and `CXX=clang++` (instead of `clang-6.0` and `clang++-6.0`).

**Comment by ehildenb** [comment]
Related PR #68
